### ISSUE TITLE
7 inch tablet is detected as a Phone and not a Tablet

### ISSUE THREAD

**Issue by kunalqss** [m0ngr31/react-native-device-detection#4] opened 2017-12-18 08:53 UTC
I am using this library for one production project at my company, and it works great for the most part.
However, now that we've added tablet support, there seems to be  a small issue seen only with 7 inch tablets (as tested on emulators and real devices). **Whenever I open my app in Portrait Mode, it detects the device as a "phone" and "isTablet" is returned false. Whereas, when I open it in landscape mode, it detects the device as a tablet, which is correct.** This issue was  not seen on 10.1 inch tablets though, so I'm assuming this has something to do with the pixel ratio on 7 inch devices ?

I am attaching the screenshots of the app when in portrait mode and in landscape mode on the same 7 inch tablet (the designs should have been the same but I am seeing mobile UI on portrait mode) -

**Portrait Mode -**

![screenshot_1513586962](https://user-images.githubusercontent.com/33343995/34097307-b67ab6b0-e3fe-11e7-8c52-2af39ea170ff.png)

**Landscape Mode -** 

![screenshot_1513586971](https://user-images.githubusercontent.com/33343995/34097310-b9a0c780-e3fe-11e7-9da3-8a5fae07c7ed.png)

**Comment by TolgaCagin** [comment] 2018-01-17 09:32
Same issue

**Comment by m0ngr31** [comment] 2018-01-18 18:17
Can you get me resolution size and pixelDensity for this tablet?

**Comment by kelset** [comment] 2018-02-08 13:43
Can confirm that this happens, just tried via Android Studio to run an emulated Nexus 7 (via AVD), these are the params:
Portrait mode:
```
adjustedHeight:1824
adjustedWidth:1200
height:912
isPhone:true
isTablet:false
pixelDensity:2
width:600
```

Looks like it's caused by the fact that even if even the simulator states that the 7' screen should be 1920, it actually isn't.

So prob to fix this line

https://github.com/m0ngr31/react-native-device-detection/blob/master/index.js#L26

Needs that 1920 to change to 1824

**Comment by m0ngr31** [comment] 2018-02-13 18:48
Go ahead and make a PR with that change and I'll get it merged and updated on npm.

**Comment by kelset** [comment] 2018-02-15 08:58
Do you think is a viable way to approach it? I mean, by looking [here](http://screensiz.es/) it seems to me that it won't fix the issue 'once and for all'.

Anyway I'll do it asap

**Comment by DevMobile2** [comment] 2019-01-21 12:48
Hi @kunalqss 
Is this issue fixed.I want to use  this in my project.
Thank you

**Comment by tvanlaerhoven** [comment] 2019-05-10 09:21
A Samsung Galaxy J6+ phone is also reported to be a tablet.
For Android it might be better to check based on the device's "smallest width", everyting in the sw600dp size bucket and above is a tablet. As described on the Android developer page: https://developer.android.com/training/multiscreen/screensizes.html#TaskUseSWQuali
See my fork for code.

**Comment by m0ngr31** [comment] 2020-01-16 17:54
Merged PR

**Closed as completed by m0ngr31** 2020-01-16 17:54 UTC
